make PROCESS_NAME=OSU350 CELL_NAME=SAMPLE PROCESS=1.0 CONDITION=TCCOM VDD=5.0 SPEED=TT	TEMP=25

#make PROCESS_NAME=NISD_BiM16_F CELL_NAME=ALEX PROCESS=1.0 CONDITION=TCCOM VDD=5.0 SPEED=TT	TEMP=25 PATH_CELL=/home/synology_nfs/Techlibs/Techlib/NISD_BiM16_F/std/fromALEX/2024_0823/spi_byLR
#make PROCESS_NAME=NISD_BiM16_F CELL_NAME=SAMPLE PROCESS=1.0 CONDITION=TCCOM VDD=5.0 SPEED=TT	TEMP=25 PATH_CELL=/home/synology_nfs/Techlibs/Techlib/NISD_BiM16_F/std/fromLR/v01.10/spice





